import type { Metadata } from "next";
import { Engagement } from "next/font/google";
import "./globals.css";

const engagement = Engagement({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${engagement.className} bg-pink-300 `}>{children}</body>
    </html>
  );
}
